_BASE_: configs_vid/youtubevis_2021/video_maskformer2_R50_bs16_8ep.yaml
MODEL:
  WEIGHTS: None
  BACKBONE:
    FREEZE_AT: -1
    NAME: "ResNetTV"
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 22
  RESNETS:
    DEPTH: 18
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  MAX_ITER: 250000
  CHECKPOINT_PERIOD: 10000
  IMS_PER_BATCH: 4
INPUT:
  SAMPLING_FRAME_NUM: 2
VERSION: 2
SEED: 42
OUTPUT_BASEDIR: '../outputs/'
FLAGS:
  CCROP: False
UNSUPVIDSEG:
  DATASET: 'KITTI'
  FLOW_LIM: 30
  RESOLUTION: 
    - 288
    - 960
  LOSS_DISP_THRESH: 0.1
